### ISSUE TITLE
NOT AN ISSUE: General Question

### ISSUE THREAD

**Issue by Kowantify** [UnRealModding/DeLogger#2]
So a particular mod is spamming some stuff in the console that unfortunately the mod dev doesn't really care about currently. is there a way in the config that you can add a custom section where we type in a partial match and it'll automatically block it aswell by chance? or does it already do that?

**Comment by Kowantify** [comment]
Also forgot to add, its through the actual Minecraft server thread, not the mods, I can block it using Mohist 1.16.5, but there's way too many issues with that software that doesn't work with my instance currently. Thankfully because it's through the main server thread you can block it, I just can't find a single 1.16.5 Forge mod that takes a users input/partial matches of a custom defined input to block something in the log, only plugins and fabric versions

**Comment by UnRealDinnerbone** [comment]
I do one day hope to add a system where you define custom loggers and such to be cancelled but not today

**Comment by UnRealDinnerbone** [comment]
Lastest version add a line in the json where you can supply the logger name to disable it

**Comment by nazzyz** [comment]
(Last comment from Aug 19)
Could you provide an example of how this new feature would work?
Example: Let's add a line in the json - and where - that will filter out logging of:
[Render thread/INFO] [antiqueatlas/]: Loaded texture antiqueatlas:mushroom with path antiqueatlas:textures/gui/tiles/mushroom.png
or
[main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `crafting_table`, expected `fastbench`. This could be a intended override, but in most cases indicates a broken mod.

both these examples write excessive lines of text in the logs that I really don't care to see.  In older versions of MC server version 1.12.2, there was a great little utility mod called "Stuff A Sock In It" https://www.curseforge.com/minecraft/mc-mods/stuff-a-sock-in-it
However, there is nothing like this for 1.16.5+ servers.
Thanks for your reply on this.

**Comment by UnRealDinnerbone** [comment]
you need to turn on the debug log, which will print the full logger name in mainDir/delogger/ then add that value to the json
as for 1.16+ there a bug in forge atm that stopping the mod from working
